const products = [
  {
    id: 1,
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    category: "treatments",
    rating: 4.6,
    description: "A lightweight facial essence featuring 96% snail secretion filtrate.",
    details: "A Korean skincare essence with a simple, lightweight texture for daily routines.",
    features: ["96% snail secretion filtrate", "Lightweight essence texture", "100 ml bottle", "Korean skincare"],
    curatorNote: "A popular Korean skincare pick with an easy-to-layer texture.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4yjkGGY",
    image: "images/416kUGx2rQL._SX679_.jpg"
  },
  {
    id: 2,
    name: "CeraVe Moisturizing Cream",
    category: "moisturizing",
    rating: 4.7,
    description: "A rich face and body cream with hyaluronic acid and ceramides.",
    details: "A versatile cream designed for face and body moisturizing routines.",
    features: ["Face and body cream", "Hyaluronic acid", "Ceramides", "Fragrance-free formula"],
    curatorNote: "A practical everyday moisturizer with a trusted reputation.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/45WZLNI",
    image: "images/61EidjXUBrL._SY450_.jpg"
  },
  {
    id: 3,
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    category: "treatments",
    rating: 4.6,
    description: "A water-based serum formulated with niacinamide and zinc PCA.",
    details: "A straightforward niacinamide serum for a targeted skincare step.",
    features: ["Niacinamide 10%", "Zinc PCA 1%", "Water-based serum", "Dropper bottle"],
    curatorNote: "An affordable and recognizable serum for a targeted routine.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/4ycMbll",
    image: "images/612NxRjAoCL._SX466_.jpg"
  },
  {
    id: 4,
    name: "CeraVe Foaming Facial Cleanser",
    category: "cleansing",
    rating: 4.7,
    description: "A foaming facial cleanser with ceramides, niacinamide and hyaluronic acid.",
    details: "A daily facial cleanser in a pump bottle for an uncomplicated cleansing step.",
    features: ["Foaming gel cleanser", "Ceramides", "Niacinamide", "Pump dispenser"],
    curatorNote: "A dependable daily cleanser for a simple skincare routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4i35TeB",
    image: "images/61w1ejKsmXL._SX466_.jpg"
  },
  {
    id: 5,
    name: "CeraVe Renewing SA Cleanser",
    category: "cleansing",
    rating: 4.6,
    description: "A salicylic acid cleanser with hyaluronic acid, niacinamide and ceramides.",
    details: "A face cleanser that brings salicylic acid into a rinse-off routine.",
    features: ["Salicylic acid", "Hyaluronic acid", "Niacinamide", "Rinse-off cleanser"],
    curatorNote: "A useful option for routines focused on cleansing and texture.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/3UzdeJ0",
    image: "images/717lRkBFR3L._SY450_.jpg"
  },
  {
    id: 6,
    name: "Neutrogena Hydro Boost Micellar Cleansing Water",
    category: "cleansing",
    rating: 4.5,
    description: "A micellar cleansing water made for a quick, no-rinse cleansing step.",
    details: "A micellar water option for removing makeup and refreshing skin before the next routine step.",
    features: ["Micellar cleansing water", "No-rinse format", "Hydro Boost line", "Bottle dispenser"],
    curatorNote: "A convenient choice for quick makeup removal and cleansing.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4x6hcGC",
    image: "images/71F5-vrxyRL._SY879_.jpg"
  },
  {
    id: 7,
    name: "COSRX Advanced Snail 92 All In One Cream",
    category: "moisturizing",
    rating: 4.5,
    description: "A facial cream featuring 92% snail secretion filtrate.",
    details: "A cream-format follow-up for routines built around COSRX snail mucin products.",
    features: ["92% snail secretion filtrate", "Cream texture", "Face moisturizer", "Korean skincare"],
    curatorNote: "A natural companion to a snail mucin skincare routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4xsWrWA",
    image: "images/71Msn18lZcL._SY450_.jpg"
  },
  {
    id: 8,
    name: "CeraVe PM Facial Moisturizing Lotion",
    category: "moisturizing",
    rating: 4.7,
    description: "An oil-free facial lotion with hyaluronic acid, niacinamide and ceramides.",
    details: "A lightweight facial lotion intended for an evening moisturizing step.",
    features: ["PM facial lotion", "Oil-free formula", "Hyaluronic acid", "Niacinamide"],
    curatorNote: "A simple lightweight moisturizer for nighttime routines.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4gyzoE0",
    image: "images/61ZCYK4subL._SY741_.jpg"
  },
  {
    id: 9,
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    category: "moisturizing",
    rating: 4.6,
    description: "A water-based hydrating serum with hyaluronic acid and vitamin B5.",
    details: "A simple serum step with a lightweight texture for layering within a skincare routine.",
    features: ["Hyaluronic acid 2%", "Vitamin B5", "Water-based serum", "Dropper bottle"],
    curatorNote: "An affordable hydration-focused addition to a routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/3UvIOaH",
    image: "images/61Se8Z9n4oL._SX466_.jpg"
  },
  {
    id: 10,
    name: "Starface Hydro-Stars Pimple Patches",
    category: "treatments",
    rating: 4.5,
    description: "Hydrocolloid pimple patches in Starface's signature star shape.",
    details: "A recognizable hydrocolloid patch format for a targeted skincare drawer essential.",
    features: ["Hydrocolloid patches", "Star-shaped design", "Targeted application", "Refill pack"],
    curatorNote: "A fun and highly recognizable skincare staple.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/4icFew1",
    image: "images/61H-JGJPOFL._SY450_.jpg"
  },
  {
    id: 11,
    name: "PanOxyl Acne Foaming Wash",
    category: "treatments",
    rating: 4.6,
    description: "A benzoyl peroxide foaming wash for an acne-care routine.",
    details: "A rinse-off benzoyl peroxide wash in an easy pump-bottle format.",
    features: ["Benzoyl peroxide wash", "Foaming cleanser", "Pump bottle", "Acne-care routine"],
    curatorNote: "A straightforward choice for an acne-focused routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4xR8NIx",
    image: "images/71I9gtceY8L._SY450_.jpg"
  },
  {
    id: 12,
    name: "The Ordinary Glycolic Acid 7% Exfoliating Toner",
    category: "treatments",
    rating: 4.5,
    description: "A glycolic acid toning solution with a 7% concentration.",
    details: "A liquid toner format for routines that include a glycolic acid step.",
    features: ["Glycolic acid 7%", "Liquid toner", "Large bottle", "Targeted skincare step"],
    curatorNote: "A recognizable exfoliating step for more focused routines.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4qYV8wb",
    image: "images/51bC4vVdkOL._SX466_.jpg"
  },
  {
    id: 13,
    name: "Differin Adapalene Gel 0.1%",
    category: "treatments",
    rating: 4.6,
    description: "An adapalene gel formulated for an acne-care routine.",
    details: "A gel-format treatment product for shoppers specifically looking for adapalene.",
    features: ["Adapalene gel 0.1%", "Tube format", "Targeted treatment", "Acne-care routine"],
    curatorNote: "A focused treatment option for shoppers seeking a specific active ingredient.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4zPOgoN",
    image: "images/61G3FDAnC8L._SY355_.jpg"
  },
  {
    id: 14,
    name: "CeraVe AM Facial Moisturizing Lotion SPF 50",
    category: "sun-care",
    rating: 4.6,
    description: "A daytime facial lotion with broad-spectrum SPF 50 and ceramides.",
    details: "A daytime moisturizer and sunscreen format for a streamlined morning routine.",
    features: ["Broad-spectrum SPF 50", "Daytime facial lotion", "Ceramides", "Pump dispenser"],
    curatorNote: "A practical morning product that combines moisturizing and sun protection.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4zWzcWO",
    image: "images/61msVAtaNPL._SX466_.jpg"
  },
  {
    id: 15,
    name: "La Roche-Posay Anthelios Melt-In Milk Sunscreen SPF 60",
    category: "sun-care",
    rating: 4.6,
    description: "A broad-spectrum sunscreen lotion with SPF 60.",
    details: "A sunscreen lotion from La Roche-Posay's Anthelios line for face and body use.",
    features: ["Broad-spectrum SPF 60", "Lotion format", "Anthelios line", "Face and body use"],
    curatorNote: "A recognizable sunscreen pick with strong everyday appeal.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/46C2Y5q",
    image: "images/61pNJwG1erL._SY450_.jpg"
  },
  {
    id: 16,
    name: "EltaMD UV Clear Facial Sunscreen SPF 46",
    category: "sun-care",
    rating: 4.7,
    description: "An oil-free facial sunscreen with zinc oxide, niacinamide and SPF 46.",
    details: "A lightweight facial sunscreen in a pump bottle for a dedicated daily sun-care step.",
    features: ["Broad-spectrum SPF 46", "Zinc oxide", "Niacinamide", "Oil-free formula"],
    curatorNote: "A premium facial sunscreen for a more elevated routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4zRbH12",
    image: "images/613YEAluowL._SX466_.jpg"
  },
  {
    id: 17,
    name: "BIODANCE Bio-Collagen Real Deep Mask",
    category: "masks",
    rating: 4.5,
    description: "A hydrogel facial mask from BIODANCE's bio-collagen range.",
    details: "An overnight-style hydrogel mask for a more deliberate skincare session.",
    features: ["Hydrogel mask", "Bio-collagen range", "Facial mask", "Single-use format"],
    curatorNote: "A highly visual mask that fits modern skincare trends.",
    badge: "New",
    featured: true,
    amazonUrl: "https://amzn.to/4x6EXy9",
    image: "images/51ubxqzNGIL._SY355_.jpg"
  },
  {
    id: 19,
    name: "Mediheal Essential Mask Sheet Set",
    category: "masks",
    rating: 4.5,
    description: "A set of Mediheal sheet masks with hydrating formulas.",
    details: "A convenient sheet-mask set for a simple, single-use skincare moment.",
    features: ["Sheet mask set", "Hydrating formulas", "Single-use masks", "Mediheal range"],
    curatorNote: "An easy entry point into Korean sheet-mask skincare.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4qQ4lHa",
    image: "images/710pdbo9-QL._SY355_.jpg"
  },
  {
    id: 20,
    name: "Kitsch Stainless Steel Gua Sha Facial Tool",
    category: "tools",
    rating: 4.5,
    description: "A stainless steel gua sha tool designed for facial massage routines.",
    details: "A durable facial massage tool with a smooth stainless steel finish.",
    features: ["Stainless steel", "Gua sha shape", "Facial massage tool", "Reusable design"],
    curatorNote: "A sleek beauty tool that looks great in a modern collection.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4xy1BRh",
    image: "images/71y1S7ZvoSL._AC_SX466_.jpg"
  },
  {
    id: 21,
    name: "Ice Roller for Face",
    category: "tools",
    rating: 4.4,
    description: "A reusable facial ice roller for a cooling massage step.",
    details: "A compact cooling roller that fits easily into a morning or evening routine.",
    features: ["Reusable roller", "Cooling facial tool", "Massage format", "Compact handle"],
    curatorNote: "A simple and visually appealing beauty tool.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4x2Mzlk",
    image: "images/61VtpMKBtVL._SY355_.jpg"
  },
  {
    id: 22,
    name: "PRITECH Electric Facial Cleansing Brush",
    category: "tools",
    rating: 4.3,
    description: "A rechargeable, waterproof electric facial cleansing brush.",
    details: "A handheld cleansing device with a rechargeable design and waterproof construction.",
    features: ["Rechargeable device", "Waterproof design", "Vibrating brush", "Handheld format"],
    curatorNote: "A more tech-focused option for an upgraded skincare setup.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4yak2Lz",
    image: "images/61Q-2hny74L._AC_SX466_.jpg"
  },
  {
    id: 23,
    name: "eos Shea Better Body Lotion, Vanilla Cashmere",
    category: "body-care",
    rating: 4.7,
    description: "A body lotion from eos with a Vanilla Cashmere scent.",
    details: "A generously sized body lotion for a daily body-care routine.",
    features: ["Body lotion", "Vanilla Cashmere scent", "Shea Better line", "Pump bottle"],
    curatorNote: "A youthful body-care pick with standout packaging and scent appeal.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/4yfmvEv",
    image: "images/61IQUadfGEL._SY450_.jpg"
  },
  {
    id: 24,
    name: "CeraVe SA Body Wash",
    category: "body-care",
    rating: 4.6,
    description: "A salicylic acid body wash with ceramides and hyaluronic acid.",
    details: "A body cleanser that brings salicylic acid into the shower routine.",
    features: ["Salicylic acid", "Body wash", "Ceramides", "Hyaluronic acid"],
    curatorNote: "A useful treatment-style body cleanser for everyday routines.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/46zdkmB",
    image: "images/51mbLoi5RIL._SY879_.jpg"
  },
  {
    id: 25,
    name: "Sol de Janeiro Brazilian Bum Bum Cream",
    category: "body-care",
    rating: 4.6,
    description: "A fast-absorbing body cream from Sol de Janeiro's Brazilian Bum Bum line.",
    details: "A body cream with the brand's iconic, sensorial presentation for a daily ritual.",
    features: ["Body cream", "Fast-absorbing texture", "Sol de Janeiro line", "Jar packaging"],
    curatorNote: "A highly recognizable premium body-care product.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4x5PSse",
    image: "images/61VhV3+-HwL._SX466_.jpg"
  },
  {
    id: 26,
    name: "Mielle Rosemary Mint Scalp & Hair Strengthening Oil",
    category: "hair-scalp",
    rating: 4.6,
    description: "A hair oil with rosemary, mint and biotin for scalp and hair routines.",
    details: "A lightweight bottle of hair oil for a focused scalp and hair-care step.",
    features: ["Rosemary and mint", "Biotin", "Scalp and hair oil", "Dropper bottle"],
    curatorNote: "A recognizable hair-care favorite with strong youth appeal.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/46C39O8",
    image: "images/61JBgQvsWtL._SY450_.jpg"
  },
  {
    id: 27,
    name: "Olaplex No. 3 Hair Perfector",
    category: "hair-scalp",
    rating: 4.6,
    description: "A pre-shampoo hair treatment from the Olaplex No. 3 range.",
    details: "A treatment-format product designed to be used before shampooing.",
    features: ["Pre-shampoo treatment", "No. 3 Hair Perfector", "Hair-care step", "Olaplex range"],
    curatorNote: "A well-known premium treatment for damaged-looking hair.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/3Uv2NGu",
    image: "images/610sljWCCzL._SX466_.jpg"
  },
  {
    id: 28,
    name: "The Ordinary Vitamin C Suspension 23% + HA Spheres 2%",
    category: "face-care",
    rating: 4.5,
    description: "A high-strength vitamin C treatment formulated with 23% pure L-ascorbic acid and 2% hyaluronic acid spheres.",
    details: "A water-free formula designed to brighten the appearance of dull skin and improve the look of uneven skin tone.",
    features: ["23% Pure L-Ascorbic Acid", "2% Hyaluronic Acid Spheres", "Brightening treatment", "Helps improve uneven skin tone"],
    curatorNote: "A high-strength vitamin C treatment for a brighter, more even-looking complexion.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/3SIYczX",
    image: "images/51LloWpF62L._SX522_.jpg"
 },
 {
    id: 29,
    name: "medicube PDRN Pink Peptide Serum",
    category: "face-care",
    rating: 4.5,
    description: "A pink glow serum formulated with PDRN, peptides, and niacinamide for hydrated, firm-looking skin.",
    details: "A lightweight Korean skincare serum designed to improve hydration, uneven skin tone, elasticity, and overall skin radiance.",
    features: ["Salmon DNA PDRN", "Five peptide complex", "Niacinamide", "Hydrating formula", "Helps improve uneven skin tone", "Korean skincare"],
    curatorNote: "A standout Korean skincare serum for a hydrated, smoother, and more radiant-looking complexion.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4x5Z7sp",
    image: "images/615DOoCI6xL._SX679_.jpg"
  },
  {
    id: 30,
    name: "Maybelline Lash Sensational Sky High Mascara",
    category: "beauty-essentials",
    rating: 4.5,
    description: "A volumizing and lengthening mascara from Maybelline's Sky High line.",
    details: "A black mascara with a flexible brush for a defined eye-makeup step.",
    features: ["Black mascara", "Flexible brush", "Sky High line", "Eye-makeup essential"],
    curatorNote: "A recognizable everyday makeup pick with broad appeal.",
    badge: "Best Seller",
    featured: false,
    amazonUrl: "https://amzn.to/4ya2dfK",
    image: "images/71MQo8pHmBL._SY450_.jpg"
  },
];
